<a href="https://colab.research.google.com/github/Wish245/PyTorch_Tutorial/blob/main/tensorOp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch = my_torch.view(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [7]:
test_torch = torch.arange(10)
test_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
test_torch = test_torch.reshape(-1,5)
test_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])