<a href="https://colab.research.google.com/github/Wish245/PyTorch_Tutorial/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a

tensor([1, 2, 3, 4])

In [4]:
tensor_b

tensor([5, 6, 7, 8])

In [5]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
tensor_a - tensor_b


tensor([-4, -4, -4, -4])

In [8]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [11]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [12]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [14]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])